"""
utils/legal_brain.py — AIttorney v7
All 11 modules upgraded to use landmark judgment context.
case_comparator now uses real scraped judgment text.
"""
from config import MODEL
from utils.search import search_bare_act, search_recent_judgments

try:
    from utils.kanoon_scraper import get_landmark_judgments
    from utils.compressor import extract_landmark_holdings
    ENHANCED = True
except ImportError:
    ENHANCED = False


def _safe(prompt: str) -> str:
    try:
        resp = MODEL.generate_content(prompt)
        return resp.text if resp.parts else "⚠️ Response blocked."
    except Exception as e:
        return f"❌ API Error: {e}"


# ── 1. LEGAL BRIEF ────────────────────────────────────────────
def generate_legal_brief(
    query: str,
    live_context: str,
    score_data: dict,
    laws_text: str,
    party_name: str = "Complainant",
    landmarks: list[dict] | None = None,
) -> str:
    lm_block = ""
    if landmarks:
        lm_block = "\nLandmark precedents to cite:\n" + "\n".join(
            f"• {lm['title']} ({lm.get('court','')}, {lm.get('date','')})"
            for lm in landmarks[:3]
        )

    return _safe(f"""
Draft a structured legal brief for an advocate in India.
Educational purposes only — mandatory advocate review before use.

Facts: {query}
Applicable Laws: {laws_text}
Win Probability: {score_data.get('probability','N/A')}% ({score_data.get('grade','')})
Context: {live_context[:2000]}
{lm_block}
Party: {party_name}

---
LEGAL BRIEF — EDUCATIONAL DRAFT
Case Reference: [Placeholder — advocate to assign]
Date: [Date]
Prepared For: {party_name}

I. STATEMENT OF FACTS
[5 numbered factual statements from the query — specific dates/amounts if mentioned]

II. ISSUES OF LAW
[3 precise legal questions this case raises]

III. APPLICABLE STATUTES & PRECEDENTS
[Each law with section number + one-line applicability note]
[Any landmark cases found above — cite them here]

IV. ARGUMENTS IN FAVOUR OF {party_name.upper()}
[4 numbered arguments citing specific provisions and precedents]

V. ANTICIPATED COUNTER-ARGUMENTS & REBUTTALS
[2 opposing arguments with specific rebuttals]

VI. RELIEF SOUGHT
[Specific relief: amount/injunction/compensation]

VII. RECOMMENDATION
[1 paragraph: recommended action + realistic outcome]
---
Generated by AIttorney. Mandatory review by licensed advocate before any use.
---
""")


# ── 2. OPPONENT ANALYSIS ──────────────────────────────────────
def analyze_opponent(query: str, live_context: str) -> str:
    return _safe(f"""
Devil's advocate legal analyst. Steelman the OPPOSING PARTY as strongly as possible.
Case: {query}
Context: {live_context[:1500]}

### What the Other Side Will Argue
[4 numbered arguments — make them genuinely strong, not strawmen]

### Their Single Most Dangerous Point
[1 paragraph on the argument most likely to hurt you in court]

### Your Specific Vulnerabilities
• [Concrete weakness — not generic]
• [Another specific weakness]
• [Third weakness]

### Counter-Strategy for Each Argument
[Numbered list — specific legal counter for each of their 4 arguments]

### Evidence They'll Deploy Against You
[Documents/witnesses the opposition will likely produce]

### Settle or Fight?
Fight if: [specific conditions that make litigation worthwhile]
Settle if: [conditions that make settlement smarter]

Educational analysis only. Advocate review mandatory.
""")


# ── 3. EVIDENCE CHECKLIST ─────────────────────────────────────
def evidence_checklist(query: str, case_type: str = "general") -> str:
    return _safe(f"""
Indian legal paralegal creating a case-specific evidence checklist.
Every item must relate directly to: {query}
Case type: {case_type}

### 🔴 Critical — Must Have (Case fails without these)
        [Document] — [Why essential + exactly how/where to get it]
        [Document] — [...]
        [Document] — [...]

### 🟡 Important — Should Have
        [Document] — [How it strengthens + how to obtain]
        [Document] — [...]

### 🟢 Supportive — Good to Have
        [Document] — [Corroborative value]
        [Document] — [...]

### 📱 Digital Evidence
        WhatsApp messages — [Specifically what to screenshot and preserve]
        Emails — [What email chain is relevant]
        UPI/bank records — [Exactly which transactions to print]
        Call logs — [If relevant]

### 👥 Witnesses
        [Type of witness] — [What they can specifically testify to]
        [Another witness type] — [Testimony scope]

### ⚠️ Preserve Immediately
[Time-sensitive evidence that can disappear — act within 24-48 hours]

### ⏰ Limitation Period
[Exact time limit for {case_type} cases in India + when your clock started]
""")


# ── 4. STATUTE EXPLAINER ──────────────────────────────────────
def explain_statute(statute_text: str) -> str:
    ctx, _ = search_bare_act(statute_text[:120])
    return _safe(f"""
Legal educator explaining an Indian law section to a complete layperson.
Law/section: {statute_text}
Web context: {ctx[:1500]}

### Plain English Summary
[3 sentences — what this law says in everyday language, no jargon]

### What Must Be Proved For This Section to Apply
1. [Element 1 — be specific]
2. [Element 2]
3. [Element 3]

### What This Means Practically
• [Practical implication 1]
• [Practical implication 2]
• [Practical implication 3]

### Landmark Cases That Interpreted This Law
[2-3 real cases from the context — cite full name, court, year]
[If none found: say so — never fabricate]

### Common Misunderstandings
1. [What people wrongly believe]
2. [Another misconception]

### When This Helps You vs. Hurts You
✅ Helps when: [specific scenario]
❌ Hurts when: [specific scenario]
""")


# ── 5. SETTLEMENT ESTIMATOR ───────────────────────────────────
def estimate_settlement(
    query: str,
    claim_amount: float,
    case_type: str,
    live_context: str,
) -> str:
    return _safe(f"""
Indian legal settlement analyst with knowledge of court-awarded amounts.
Case: {query}
Claim: ₹{claim_amount:,.0f}
Type: {case_type}
Context: {live_context[:1500]}

### Settlement Range
🔴 Pessimistic (weak position): ₹[amount] — [reasoning]
🟡 Realistic (average outcome): ₹[amount] — [reasoning]  
🟢 Optimistic (strong position): ₹[amount] — [reasoning]

### Basis for Estimate
[What Indian courts typically award for {case_type} cases — cite any figures from context]

### Factors That Increase Your Award
• [Factor] → adds approximately ₹[range]
• [Factor] → adds approximately ₹[range]

### Factors That Reduce Your Award
• [Factor] → reduces by ₹[range]
• [Factor] → reduces by ₹[range]

### Cost-Benefit Table
| Item | Estimate |
|------|----------|
| Legal fees (advocate) | ₹[range] |
| Court fees | ₹[range] |
| Expected timeline | [duration] |
| Net realistic outcome | ₹[award minus costs] |
| Break-even point | ₹[minimum to make litigation worthwhile] |

### Fight or Settle?
Fight if: [specific conditions]
Settle if: [specific conditions]
**Recommendation:** [1 direct sentence]

⚠️ Educational estimate only. Actual awards vary significantly by judge and facts.
""")


# ── 6. CASE STRENGTH TIMELINE ─────────────────────────────────
def case_strength_timeline(
    query: str,
    score_data: dict,
    case_type: str,
) -> list[dict]:
    raw = _safe(f"""
Legal strategist modeling case progression for an Indian lawsuit.
Case: {query}
Starting win probability: {score_data.get('probability',50)}%
Case type: {case_type}

For each stage give probability and a specific note.
EXACT format — nothing else:

STAGE: Legal Notice / Demand Letter
PROB: [0-100]
NOTE: [One specific sentence on what happens and why strength shifts]

STAGE: Filing & Court Admission
PROB: [0-100]
NOTE: [One sentence]

STAGE: Interim Relief / Stay Order
PROB: [0-100]
NOTE: [One sentence]

STAGE: Evidence & Arguments
PROB: [0-100]
NOTE: [One sentence]

STAGE: Final Judgment
PROB: [0-100]
NOTE: [One sentence]

STAGE: Appeal (if needed)
PROB: [0-100]
NOTE: [One sentence]
""")
    stages = []
    for block in raw.split("STAGE:"):
        lines = [l.strip() for l in block.strip().splitlines() if l.strip()]
        if not lines:
            continue
        name = lines[0]
        prob = 50
        note = ""
        for l in lines[1:]:
            if l.startswith("PROB:"):
                try:
                    prob = max(5, min(95, int(l.replace("PROB:","").strip().split()[0])))
                except:
                    pass
            elif l.startswith("NOTE:"):
                note = l.replace("NOTE:","").strip()
        if name:
            stages.append({"stage": name, "prob": prob, "note": note})
    return stages


# ── 7. JURISDICTION ADVISOR ───────────────────────────────────
def jurisdiction_advisor(query: str, location: str = "India") -> str:
    return _safe(f"""
Indian procedural law expert on court/forum selection.
Case: {query}
Location: {location}

### Recommended Forum
**[Forum name]** — [1 sentence: why this is optimal for this specific case]

### Why This Forum (Not Others)
[3 specific reasons this forum fits this exact case type]

### Filing Requirements
| Item | Detail |
|------|--------|
| Pecuniary limit | [₹ amount or "unlimited"] |
| Territorial jurisdiction | [Which courts cover {location}] |
| Court fee | [Approximate ₹ amount] |
| Limitation period | [Exact time limit] |
| Avg. wait for first hearing | [Weeks/months] |

### Documents to Bring on Day 1
1. [Document]
2. [Document]
3. [Document]

### Alternative Forums
1. **[Forum]** — use when [specific condition]
2. **[Forum]** — use when [specific condition]

### Lok Adalat Option
[Suitable? Why? What's the realistic outcome and timeline?]

### Next 7 Days — Concrete Actions
1. [Immediate step]
2. [Second step]

### #1 Mistake to Avoid
[The most common procedural error in this case type]
""")


# ── 8. FIR DRAFT ─────────────────────────────────────────────
def fir_draft(
    query: str,
    complainant: str,
    accused_desc: str,
    location: str,
) -> str:
    return _safe(f"""
Draft a formal police complaint / FIR application for India.
Educational purposes only — must be reviewed before submission.

Complainant: {complainant or '[Your Full Name]'}
Situation: {query}
Accused: {accused_desc or '[Accused description]'}
Location: {location}

---
FIR APPLICATION DRAFT
---

TO,
The Station House Officer,
[Nearest Police Station], {location}

Subject: Complaint for registration of FIR under [sections] regarding [brief subject]

Respected Sir/Madam,

I, {complainant or '[Your Full Name]'}, resident of [Address], wish to lodge a 
formal complaint against [accused] for the following:

CHRONOLOGICAL FACTS:
[7 numbered statements — specific dates, amounts, places from the situation]

APPLICABLE SECTIONS:
[List IPC/BNS sections with one-line reason each]
• Section [X] IPC/BNS — [reason]
• Section [Y] IT Act — [reason if cyber crime]

RELIEF REQUESTED:
1. Register an FIR under the above sections immediately
2. [Specific investigation request]
3. [Any interim protection if domestic violence/threats]

DECLARATION:
I affirm that the above facts are true to the best of my knowledge and belief.
I am willing to provide further evidence as required.

[Complainant Signature]
[Full Name]
[Date]
[Contact Number]
[Aadhaar/ID Number if required]

---
JURISDICTION NOTE: [Which police station has jurisdiction and why]
DOCUMENTS TO BRING: [What to carry when filing]
IF POLICE REFUSE TO FILE: [Options — Magistrate complaint, SP office, online portal]
---
Generated by AIttorney for educational purposes only.
Have this reviewed by a licensed advocate before submission.
---
""")


# ── 9. MEDIATION SCRIPT ───────────────────────────────────────
def mediation_script(
    query: str,
    your_position: str,
    other_party: str,
    ideal_outcome: str,
) -> str:
    return _safe(f"""
Experienced mediation coach preparing a party for pre-litigation negotiation in India.
Dispute: {query}
Your position: {your_position or 'Aggrieved party seeking resolution'}
Other party: {other_party or 'Opposing party'}
Ideal outcome: {ideal_outcome or 'Fair resolution'}

### Your Opening Statement (Read this aloud)
[3-4 sentences: state the dispute factually, acknowledge the relationship if any,
signal willingness to resolve — firm but non-aggressive]

### Your Core Demands (Priority order)
1. **Non-negotiable:** [What you absolutely must get]
2. **Important:** [What you strongly want but could compromise on by 20%]
3. **Preferred:** [What would be nice but you can fully concede]

### Concessions You Can Offer
• [What you're willing to give up to reach agreement]
• [Another reasonable concession that costs you little]

### Handling Their Objections
**If they say:** "[Most likely objection]"
**You respond:** "[Calm, firm counter]"

**If they say:** "[Second likely objection]"  
**You respond:** "[Counter]"

### Your Red Lines (Never concede these)
• [Absolute minimum you'll accept]
• [Another firm boundary]

### Closing Language If Agreement Reached
"We agree that [party] will [action] by [date], and [party] will [action] by [date].
This agreement is in full and final settlement of the dispute."

### If Mediation Fails — Next Step
[Exact next legal action + recommended timeline to file]

### Psychological Tactics for This Dispute
1. [Specific tactic for this type of conflict]
2. [Second tactic]
3. [Third tactic]
""")


# ── 10. LIMITATION CHECKER ───────────────────────────────────
def limitation_checker(
    case_type: str,
    incident_date: str,
    query: str,
) -> str:
    ctx, _ = search_recent_judgments(
        f"{case_type} limitation period condonation India", 2020
    )
    return _safe(f"""
Indian limitation period expert.
Case type: {case_type}
Incident date: {incident_date}
Situation: {query}
Recent court context: {ctx[:800]}

### Applicable Limitation Period
**Governing law:** [Limitation Act 1963 / specific act section]
**Standard limit for {case_type}:** [exact period]
**Clock starts from:** [when — common mistake: people think wrong start date]

### Your Deadline
Event date: {incident_date}
Filing deadline: [calculated date]
Time remaining: [days/months OR "EXPIRED — see options below"]

### ⚠️ Urgency Level
[🔴 CRITICAL — file within days / 🟡 ACT SOON — weeks / 🟢 Time available]

### If Time Has Passed — Can You Still File?
Section 5, Limitation Act: [what courts look for to excuse delay]
Recent precedents on condonation from context above.

### Common Mistakes on Start Date
[What people wrongly think starts the clock vs what actually does]

### Immediate Steps
1. [Most urgent action]
2. [Second step]

### If Already Time-Barred
[Alternative remedies: consumer forum vs civil court vs criminal route]

⚠️ Consult a lawyer immediately if deadline is near or has passed.
""")


# ── 11. CASE COMPARATOR ───────────────────────────────────────
def case_comparator(
    query: str,
    live_context: str,
    case_type: str,
) -> str:
    """
    Now uses real scraped landmark judgments if available.
    Falls back to search-based comparison otherwise.
    """
    landmark_context = ""
    if ENHANCED:
        try:
            landmarks = get_landmark_judgments(query, case_type)
            if landmarks:
                landmark_context = extract_landmark_holdings(landmarks, query)
        except Exception:
            pass

    recent_ctx, _ = search_recent_judgments(
        f"{case_type} {query[:60]}", 2019
    )
    combined = live_context[:1000] + "\n\n" + recent_ctx[:800]
    if landmark_context:
        combined = f"LANDMARK HOLDINGS:\n{landmark_context}\n\n" + combined

    return _safe(f"""
Senior Indian legal researcher comparing user facts to decided cases.
User situation: {query}
Case type: {case_type}
Available context (includes landmark judgments where found):
{combined}

### Comparison to Decided Cases

For each comparable case found:
**[Case Name] ([Court], [Year]) — [Citation count if known] citations**
Facts: [Brief facts of that case]
Ruling: [What the court decided — be specific]
Similarity to your case: [High/Medium/Low] — [Why]
Implication for you: [How that ruling helps or hurts your claim]

### Strongest Precedent IN Your Favour
[Name the single best case supporting your position — cite properly]
[Why it directly applies to your facts]

### Strongest Precedent AGAINST You
[Case the other side will cite — cite properly]
[How to distinguish your facts from that case]

### Judicial Trend 2020–2025
[Have courts been more or less sympathetic to cases like yours recently?
Any significant shift in how courts interpret this area of law?]

### The Legal Test Courts Apply
[The specific legal standard courts use for {case_type} cases]
[What you must prove to satisfy it]

### How to Distinguish Unfavourable Cases
[Specific argument for why your facts differ from adverse precedents]

Note: Verify all citations independently. Never rely solely on AI for case citations.
""")