
import io
from datetime import datetime

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer,
        HRFlowable, Table, TableStyle
    )
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_notice_pdf(notice_text: str, metadata: dict) -> bytes | None:
    """
    Returns PDF bytes or None if reportlab not installed.
    metadata keys: sender, recipient, tone, date
    """
    if not REPORTLAB_AVAILABLE:
        return None

    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2.8*cm, leftMargin=2.8*cm,
        topMargin=2.5*cm,   bottomMargin=2.2*cm,
        title="Legal Notice — AIttorney",
        author="AIttorney Platform",
    )

    # ── Colours ────────────────────────────────────────────
    GOLD  = colors.HexColor("#A87828")
    NAVY  = colors.HexColor("#1B2236")
    GREY  = colors.HexColor("#485068")
    LIGHT = colors.HexColor("#F5F0E8")

    # ── Styles ─────────────────────────────────────────────
    styles   = getSampleStyleSheet()
    heading  = ParagraphStyle("H", parent=styles["Heading1"],
                               fontSize=20, textColor=NAVY,
                               fontName="Times-Bold", spaceAfter=2,
                               leading=24)
    subhead  = ParagraphStyle("SH", parent=styles["Normal"],
                               fontSize=9, textColor=GOLD,
                               fontName="Helvetica", letterSpacing=2,
                               spaceAfter=0)
    body     = ParagraphStyle("B", parent=styles["Normal"],
                               fontSize=10.5, leading=17,
                               textColor=GREY, spaceAfter=4)
    bold_body= ParagraphStyle("BB", parent=body,
                               fontName="Helvetica-Bold", textColor=NAVY)
    footer_s = ParagraphStyle("F", parent=styles["Normal"],
                               fontSize=7.5, textColor=colors.grey,
                               alignment=1, leading=11)

    # ── Story ──────────────────────────────────────────────
    story = []

    # Header table: logo left, date right
    date_str = metadata.get("date", datetime.now().strftime("%d %B %Y"))
    header_data = [[
        Paragraph("⚖️ <b>AIttorney</b>", ParagraphStyle("Logo",
            parent=styles["Normal"], fontSize=13, textColor=GOLD,
            fontName="Helvetica-Bold")),
        Paragraph(f"Date: {date_str}", ParagraphStyle("DateS",
            parent=styles["Normal"], fontSize=9, textColor=GREY,
            alignment=2))
    ]]
    header_tbl = Table(header_data, colWidths=["60%", "40%"])
    header_tbl.setStyle(TableStyle([
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(header_tbl)
    story.append(HRFlowable(width="100%", thickness=1.5, color=GOLD, spaceAfter=14))

    # Title
    story.append(Paragraph("LEGAL NOTICE", heading))
    story.append(Paragraph(f"TONE: {metadata.get('tone','Professional').upper()}", subhead))
    story.append(Spacer(1, 0.35*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=14))

    # Body — split on newlines, bold lines that look like headers
    for line in notice_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 0.18*cm))
            continue
        is_header = (
            stripped.isupper() or
            stripped.startswith("Subject:") or
            stripped.startswith("Re:") or
            (len(stripped) < 60 and stripped.endswith(":"))
        )
        style_to_use = bold_body if is_header else body
        story.append(Paragraph(stripped, style_to_use))

    # Footer
    story.append(Spacer(1, 0.6*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=8))
    story.append(Paragraph(
        "This document was generated by AIttorney for educational/demonstration purposes only. "
        "It does not constitute legal advice. Please have this reviewed by a licensed advocate "
        "before sending. AIttorney is not liable for any action taken based on this document.",
        footer_s
    ))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Generated by AIttorney v3.0 · {datetime.now().strftime('%d %b %Y, %H:%M')}",
        footer_s
    ))

    doc.build(story)
    return buffer.getvalue()