"""utils/ai.py — Core Gemini calls (case analysis, audit, notice, roadmap)."""
from config import MODEL

def _safe(prompt: str) -> str:
    try:
        r = MODEL.generate_content(prompt)
        return r.text if r.parts else "⚠️ Response blocked by safety filters."
    except Exception as e:
        return f"❌ API Error: {e}"

def analyze_case(query: str, live_context: str, language: str) -> str:
    return _safe(f"""
Educational legal assistant for India. Clear, direct, genuinely useful.
Live court records: {live_context}
Situation: {query}
Language: {language}

### Summary
2-3 sentences on what this situation is legally.
### Your Legal Position
Strong or weak case and why. Be honest.
### Key Laws That Apply
2-4 specific sections with one-line explanations.
### What You Should Do Next
4 numbered concrete steps, most urgent first.
### Realistic Expectations
Timeline, cost estimate, likely outcome.

End: "Please consult a licensed advocate before taking legal action."
""")

def get_applicable_laws(query: str) -> str:
    return _safe(f"""
Legal situation in India: "{query}"
List 3-5 directly applicable laws/sections:
• [Act Name] Section [X] — [what it covers and why it applies]
Specific only. No padding.
""")

def get_similar_cases(query: str, context: str) -> str:
    return _safe(f"""
Situation: "{query}"
Context: {context[:2000]}
Name 1-2 specific Indian court cases with relevant precedent.
For each: Case name, court, year, why relevant.
If none found in context, say so honestly. Do not fabricate.
""")

def audit_contract(text: str, role: str) -> str:
    return _safe(f"""
Strict legal auditor for a {role} in India.
Identify 3 critical issues. For each:
🔴 HIGH RISK — [Clause Name]
Problem: [Why it hurts a {role}]
Fair version: [Balanced alternative]
OR 🟡 MEDIUM RISK — same format.
Then: Overall verdict + top negotiation priority.
Contract: {text}
""")

def chat_with_contract(question: str, context: str) -> str:
    return _safe(f"""
Answer about this contract. Direct. Cite clause if possible.
If not in document: "This isn't addressed in the contract."
Contract: {context}
Question: {question}
""")

def summarize_for_layman(text: str) -> str:
    return _safe(f"""
Translate to plain English. Short sentences. Explain jargon in brackets.
Text: {text[:4000]}
Format: Plain Summary: [2-3 sentences]
Key Points: • [point] • [point]
Important Terms: [term: meaning]
""")

def draft_notice(context: str, sender: str, recipient: str, tone: str) -> str:
    tones = {
        "Professional": "Formal and measured. Polite. Leaves room for goodwill.",
        "Strict":        "Assertive. Hard 15-day deadline. Serious consequences implied.",
        "Final Warning": "Last chance. Imminent legal action. No ambiguity."
    }
    return _safe(f"""
Draft formal legal notice. Educational only.
Issue: {context}
From: {sender or '[Sender Name]'}
To: {recipient or '[Recipient Name]'}
Tone: {tones.get(tone, tones['Professional'])}
Jurisdiction: India
Structure: Header → Background → Grievance → Legal Demand → Consequence → Closing
End with: "Generated by AIttorney for educational purposes only."
""")

def generate_roadmap(situation: str, jurisdiction: str) -> str:
    return _safe(f"""
Legal issue in {jurisdiction}: "{situation}"
4-step plan. Format EXACTLY:
STEP 1: [Title]
Action: [2 sentences]
Law: [Section/act or N/A]
Timeline: [Estimate]
STEP 2: ... STEP 3: ... STEP 4: ...
India-specific. Educational only.
""")