"""
utils/legal_brain.py — AIttorney v6
11 AI-powered legal intelligence modules.
Each has its own prompt architecture, search strategy, structured output.
These are the features that make this an MVP, not a wrapper.

Modules:
  1.  generate_legal_brief()       — advocate-ready structured brief
  2.  analyze_opponent()           — steelman opposing arguments + counters
  3.  evidence_checklist()         — case-specific documents to gather
  4.  explain_statute()            — plain-English law explainer with cases
  5.  estimate_settlement()        — ₹ range based on Indian court patterns
  6.  case_strength_timeline()     — probability at each litigation stage
  7.  jurisdiction_advisor()       — which court/forum + filing requirements
  8.  fir_draft()                  — FIR complaint draft with IPC/BNS sections
  9.  mediation_script()           — talking points for pre-litigation mediation
  10. limitation_checker()         — time-left-to-file calculator with warnings
  11. case_comparator()            — compare your facts to similar decided cases
"""
from config import MODEL
from utils.search import search_bare_act, search_recent_judgments


def _safe(prompt: str) -> str:
    try:
        resp = MODEL.generate_content(prompt)
        return resp.text if resp.parts else "⚠️ Response blocked by safety filters."
    except Exception as e:
        return f"❌ API Error: {e}"


# ═══════════════════════════════════════════════════════════
# 1. LEGAL BRIEF GENERATOR
# ═══════════════════════════════════════════════════════════
def generate_legal_brief(query: str, live_context: str,
                          score_data: dict, laws_text: str,
                          party_name: str = "Complainant") -> str:
    return _safe(f"""
You are drafting a structured legal brief for an advocate in India.
Educational purposes only — must be reviewed by a licensed advocate.

Facts: {query}
Applicable Laws: {laws_text}
Win Probability: {score_data.get('probability','N/A')}% ({score_data.get('grade','')})
Live Context: {live_context[:2000]}
Party: {party_name}

Draft in EXACT structure:
---
LEGAL BRIEF — EDUCATIONAL DRAFT
Case Reference: [Placeholder ref]
Date: [Date placeholder]
Prepared For: {party_name}

I. STATEMENT OF FACTS
[5 numbered factual statements from the query]

II. ISSUES OF LAW
[3 precise legal questions this case raises]

III. APPLICABLE STATUTES & PRECEDENTS
[Each law/section + one-line applicability note]

IV. ARGUMENTS IN FAVOUR OF {party_name.upper()}
[4 numbered legal arguments citing specific provisions]

V. ANTICIPATED COUNTER-ARGUMENTS & REBUTTALS
[2 opposing arguments with brief rebuttals]

VI. RELIEF SOUGHT
[Specific relief: damages/injunction/compensation]

VII. RECOMMENDATION
[1 paragraph: recommended action + realistic outcome]
---
Note: Generated by AIttorney for educational purposes only.
Mandatory review by a licensed advocate before any use.
---
""")


# ═══════════════════════════════════════════════════════════
# 2. OPPONENT ARGUMENT ANALYZER
# ═══════════════════════════════════════════════════════════
def analyze_opponent(query: str, live_context: str) -> str:
    return _safe(f"""
Devil's advocate legal analyst. Steelman the OPPOSING PARTY as strongly as possible.
Case: {query}
Context: {live_context[:1500]}

### What the Other Side Will Argue
[4 numbered arguments — make them strong and honest]

### Their Single Most Dangerous Point
[1 paragraph on the argument most likely to hurt you in court]

### Your Vulnerabilities
• [Specific weakness in your position]
• [Another weakness]
• [Another weakness]

### Counter-Strategy for Each Argument
[Numbered list matching their arguments — specific legal counters]

### Evidence They'll Deploy Against You
[Documents/witnesses the opposition will likely produce]

### Settlement Vs. Fight Recommendation
[Given the opposing strength, should you settle or litigate? Why?]

Educational analysis. An advocate must review before any action.
""")


# ═══════════════════════════════════════════════════════════
# 3. EVIDENCE CHECKLIST
# ═══════════════════════════════════════════════════════════
def evidence_checklist(query: str, case_type: str = "general") -> str:
    return _safe(f"""
Meticulous Indian legal paralegal creating a case-specific evidence checklist.
Situation: {query}
Case type: {case_type}

### 🔴 Critical — Must Have
[ ] [Document] — [Why essential + exactly where to obtain it]
[ ] [Document] — [...]
[ ] [Document] — [...]

### 🟡 Important — Should Have
[ ] [Document] — [How it strengthens your case]
[ ] [Document] — [...]

### 🟢 Supportive — Good to Have
[ ] [Document] — [Corroborative value]
[ ] [Document] — [...]

### 📱 Digital Evidence
[ ] [Specific screenshots/messages/emails relevant to this exact case]
[ ] WhatsApp/email records — [what specifically to preserve]
[ ] Payment records — [UPI/bank statements to request]

### 👥 Witnesses Needed
[ ] [Type of witness + what they testify to]
[ ] [Another witness type]

### ⚠️ Preserve Immediately — Time-Sensitive
[Evidence that disappears fast — act within days not weeks]

### ⏰ Limitation Period Alert
[Exact time limit to file this type of case in India + today's deadline math]

Every item must be specific to the situation described. No generic boilerplate.
""")


# ═══════════════════════════════════════════════════════════
# 4. STATUTE EXPLAINER (with live search)
# ═══════════════════════════════════════════════════════════
def explain_statute(statute_text: str) -> str:
    ctx, _ = search_bare_act(statute_text[:120])
    return _safe(f"""
Legal educator explaining an Indian law section to a complete layperson.
Law/section: {statute_text}
Web context on this law: {ctx[:1500]}

### Plain English Summary
[3 sentences: what this law says in everyday language]

### What This Means For You Practically
• [Practical implication 1]
• [Practical implication 2]
• [Practical implication 3]

### What Must Be Proved For This Section to Apply
1. [Element 1]
2. [Element 2]
3. [Element 3]

### Landmark Cases That Interpreted This Law
[2-3 real cases from the web context, or note if unavailable — never fabricate]

### Common Misunderstandings About This Law
1. [What people wrongly believe]
2. [Another misconception]

### When This Law Works For You vs. Against You
✅ Helps when: [scenario]
❌ Hurts when: [scenario]

No unnecessary jargon. Keep it genuinely accessible.
""")


# ═══════════════════════════════════════════════════════════
# 5. SETTLEMENT ESTIMATOR
# ═══════════════════════════════════════════════════════════
def estimate_settlement(query: str, claim_amount: float,
                         case_type: str, live_context: str) -> str:
    return _safe(f"""
Indian legal settlement analyst with deep knowledge of court-awarded amounts.
Case: {query}
Claim: ₹{claim_amount:,.0f}
Type: {case_type}
Precedent context: {live_context[:1500]}

### Settlement Range Estimate
🔴 Pessimistic: ₹[amount] — [reasoning based on weak case scenario]
🟡 Realistic: ₹[amount] — [most likely outcome]
🟢 Optimistic: ₹[amount] — [best-case scenario]

### Basis for Estimate
[What Indian courts typically award in this category of case]

### Factors That Increase Your Award
• [Factor] → adds approximately ₹[range]
• [Factor] → adds approximately ₹[range]

### Factors That Reduce Your Award
• [Factor] → reduces by ₹[range]
• [Factor] → reduces by ₹[range]

### Cost-Benefit Analysis
| Item | Amount |
|------|--------|
| Estimated legal fees to fight | ₹[range] |
| Expected timeline | [duration] |
| Realistic net award | ₹[award minus costs] |
| Break-even point | ₹[minimum to make litigation worthwhile] |

### Fight or Settle?
Fight if: [specific conditions]
Settle if: [specific conditions]
**Recommendation:** [1 direct sentence]

### Comparable Indian Court Awards
[1-2 examples from the provided context or general knowledge]

⚠️ Educational estimate based on general patterns. Actual awards vary significantly.
""")


# ═══════════════════════════════════════════════════════════
# 6. CASE STRENGTH TIMELINE
# ═══════════════════════════════════════════════════════════
def case_strength_timeline(query: str, score_data: dict, case_type: str) -> list[dict]:
    raw = _safe(f"""
Legal strategist modeling case progression for an Indian lawsuit.
Case: {query}
Current win probability: {score_data.get('probability',50)}%
Case type: {case_type}

For each stage give win probability and a note. EXACT format, nothing else:

STAGE: Legal Notice / Demand
PROB: [0-100]
NOTE: [one sentence on what happens and how it shifts strength]

STAGE: Filing & Court Admission
PROB: [0-100]
NOTE: [one sentence]

STAGE: Interim Relief / Injunction
PROB: [0-100]
NOTE: [one sentence]

STAGE: Evidence & Arguments
PROB: [0-100]
NOTE: [one sentence]

STAGE: Final Judgment
PROB: [0-100]
NOTE: [one sentence]

STAGE: Appeal (if needed)
PROB: [0-100]
NOTE: [one sentence]
""")
    stages = []
    for block in raw.split("STAGE:"):
        lines = [l.strip() for l in block.strip().splitlines() if l.strip()]
        if not lines:
            continue
        name = lines[0]
        prob = 50
        note = ""
        for l in lines[1:]:
            if l.startswith("PROB:"):
                try: prob = max(5, min(95, int(l.replace("PROB:","").strip().split()[0])))
                except: pass
            elif l.startswith("NOTE:"):
                note = l.replace("NOTE:","").strip()
        if name:
            stages.append({"stage": name, "prob": prob, "note": note})
    return stages


# ═══════════════════════════════════════════════════════════
# 7. JURISDICTION ADVISOR
# ═══════════════════════════════════════════════════════════
def jurisdiction_advisor(query: str, location: str = "India") -> str:
    return _safe(f"""
Indian procedural law expert on court/forum selection.
Case: {query}
Location: {location}

### Recommended Forum / Court
**[Forum name]** — [1 sentence why this is optimal]

### Why This Forum (Not Others)
[3 specific reasons this forum fits this exact case]

### Filing Requirements
| Item | Detail |
|------|--------|
| Pecuniary limit | [Amount jurisdiction] |
| Territorial jurisdiction | [Which courts cover this location] |
| Court fee | [Approximate amount] |
| Limitation period | [Time limit to file] |
| Time to first hearing | [Typical wait] |

### Documents to Bring When Filing
1. [Document]
2. [Document]
3. [Document]

### Alternative Forums If Primary Not Suitable
1. **[Forum]** — use when [condition]
2. **[Forum]** — use when [condition]

### Lok Adalat / Mediation Option
[Is this suitable? Expected timeline? Benefits vs. court?]

### What to Do in the Next 7 Days
[Concrete immediate action steps]

### Common Mistake to Avoid
[The #1 procedural error people make in this type of case]
""")


# ═══════════════════════════════════════════════════════════
# 8. FIR DRAFT GENERATOR  ← NEW
# ═══════════════════════════════════════════════════════════
def fir_draft(query: str, complainant: str, accused_desc: str, location: str) -> str:
    """
    Drafts a structured police complaint / FIR application.
    Identifies applicable IPC/BNS sections automatically.
    Tells user which police station has jurisdiction.
    """
    return _safe(f"""
Draft a formal police complaint / FIR application for filing in India.
This is for educational purposes — must be reviewed before submission.

Complainant: {complainant or '[Complainant Name]'}
Situation: {query}
Description of accused: {accused_desc or '[Accused description]'}
Location: {location}

Generate EXACTLY:

---
FIR APPLICATION DRAFT
---

TO,
The Station House Officer,
[Relevant Police Station], {location}

Subject: Complaint regarding [brief subject]

Respected Sir/Madam,

I, {complainant or '[Your Full Name]'}, wish to lodge a complaint against [accused] for the following:

STATEMENT OF FACTS:
[5-7 numbered factual statements in chronological order, derived from the situation]

APPLICABLE SECTIONS:
[List each IPC/BNS section that applies with a one-line reason]
• [Section X] — [why it applies]
• [Section Y] — [why it applies]

RELIEF REQUESTED:
1. Register an FIR under the above sections
2. [Specific investigation request]
3. [Any interim protection if needed]

DECLARATION:
I affirm that the above facts are true to the best of my knowledge.

[Complainant Name & Signature]
[Date]
[Contact Number]
---
JURISDICTION NOTE: [Which police station has jurisdiction and why]
IMPORTANT: [Time-sensitive action to take + any evidence to bring when filing]
NOTE: Generated by AIttorney for educational purposes only.
---
""")


# ═══════════════════════════════════════════════════════════
# 9. MEDIATION SCRIPT  ← NEW
# ═══════════════════════════════════════════════════════════
def mediation_script(query: str, your_position: str, 
                      other_party: str, ideal_outcome: str) -> str:
    """
    Generates a structured mediation talking script.
    Helps users negotiate BEFORE going to court — saves time and money.
    Includes opening statement, key demands, concessions to offer, red lines.
    """
    return _safe(f"""
Experienced mediation coach preparing a party for pre-litigation negotiation in India.
Dispute: {query}
Your position: {your_position or 'Aggrieved party seeking resolution'}
Other party: {other_party or 'Opposing party'}
Ideal outcome: {ideal_outcome or 'Fair resolution'}

Generate a practical mediation script:

### Your Opening Statement (Read this aloud to start)
[3-4 sentences: state the dispute factually, acknowledge the relationship,
signal willingness to resolve — firm but non-aggressive tone]

### Your Core Demands (In priority order)
1. **Non-negotiable:** [What you absolutely must get]
2. **Important:** [What you strongly want but could compromise on]
3. **Preferred:** [What would be nice but you can concede]

### Concessions You Can Offer
• [What you're willing to give up to reach agreement]
• [Another reasonable concession]

### How to Handle Their Likely Objections
Objection: "[Likely thing they'll say]"
Your response: "[How to counter this calmly and firmly]"

Objection: "[Another likely objection]"
Your response: "[Counter]"

### Your Red Lines (Never concede these)
• [Absolute minimum you'll accept]
• [Another red line]

### Closing Statement If Agreement Reached
[Draft acceptance language for a verbal agreement]

### If Mediation Fails
[Exact next legal step to take + recommended timeline]

### Psychological Tips for This Specific Dispute
[2-3 practical negotiation tactics suited to this type of dispute]
""")


# ═══════════════════════════════════════════════════════════
# 10. LIMITATION PERIOD CHECKER  ← NEW
# ═══════════════════════════════════════════════════════════
def limitation_checker(case_type: str, incident_date: str, query: str) -> str:
    """
    Calculates limitation period, checks if case is still fileable,
    warns about approaching deadlines.
    Searches for recent court rulings on limitation condonation.
    """
    ctx, _ = search_recent_judgments(f"{case_type} limitation period condonation India", 2020)
    return _safe(f"""
Indian limitation period expert analyzing filing deadline urgency.
Case type: {case_type}
Incident/event date: {incident_date}
Situation: {query}
Recent court context on limitation: {ctx[:1000]}

### Applicable Limitation Period
**Act:** [Limitation Act 1963 / specific act section]
**Standard time limit:** [period]
**For this specific case type ({case_type}):** [exact period]

### Your Filing Deadline
Event date: {incident_date}
Deadline to file: [calculated date]
Time remaining: [days/months remaining OR "EXPIRED"]

### ⚠️ Urgency Assessment
[🔴 CRITICAL — file within days / 🟡 ACT SOON — weeks / 🟢 Time available]

### Can You Still File If Time Has Passed?
[Section 5 Limitation Act — condonation of delay explained]
[What courts look for to excuse late filing]
[Recent cases from context where delay was/wasn't condoned]

### What Counts as the "Start Date"
[When does the clock actually start for this case type — common mistakes]

### Steps to File Before Deadline
1. [Immediate action]
2. [Next step]
3. [Filing step]

### If Already Time-Barred
[Alternative remedies still available even after limitation expires]

⚠️ Consult a lawyer immediately if deadline is near or has passed.
""")


# ═══════════════════════════════════════════════════════════
# 11. CASE COMPARATOR  ← NEW
# ═══════════════════════════════════════════════════════════
def case_comparator(query: str, live_context: str, case_type: str) -> str:
    """
    Compares the user's facts to similar decided Indian court cases.
    Extracts how those courts ruled and applies the reasoning to the user's case.
    This is the closest to genuine legal research an AI can provide.
    """
    recent_ctx, _ = search_recent_judgments(f"{case_type} {query[:60]}", 2019)
    combined_ctx  = live_context[:1500] + "\n\n" + recent_ctx[:1000]
    return _safe(f"""
Senior Indian legal researcher comparing user facts to decided cases.
User's situation: {query}
Case type: {case_type}
Available case context: {combined_ctx}

### How Your Case Compares to Decided Cases

For each comparable case found in context:

**Case [N]: [Case name, court, year]**
Facts: [Brief facts of that case]
Ruling: [What the court decided]
Similarity to your case: [High/Medium/Low] — [Why]
What this means for you: [How that ruling helps or hurts your claim]

### The Strongest Precedent In Your Favour
[Name the single best case supporting your position and why]

### The Strongest Precedent Against You
[Name the case most likely to be cited by the other side]

### How Courts Have Trended Recently (2020-2025)
[Have courts been more or less sympathetic to cases like yours? Any pattern?]

### Key Legal Principle Your Case Must Satisfy
[The core legal test courts apply in cases like this]

### Distinguishing Unfavourable Precedents
[How to argue your facts are different from cases that went against similar claimants]

Note: Based on available web context. Always verify case citations independently.
""")